### ISSUE TITLE
SWIFT_VERSION = 3 warning

### ISSUE THREAD

**Issue by Ruckt** [drtimcooper/LatLongToTimezone#15]
After installing your pod, I am getting the following warning for each of my targets. 

```
[!] The `Cookie Van [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-Cookie Van/Pods-Cookie Van.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

At the bottom of this post you can find out an examination of the issue: https://github.com/CocoaPods/CocoaPods/issues/5952

In sum, you should use pod_target_xcconfig instead of xcconfig in the podspec as detailed here: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/814

**Comment by akirmse** [comment]
I fixed this and increased the version number to 1.1.2.  I found that I needed to upgrade to cocoapods 1.1 to get the pod to buidl correctly.
