### ISSUE TITLE
Objective-C compatibility

### ISSUE THREAD

**Issue by alecvance** [drtimcooper/LatLongToTimezone#18]
Hi there! 

To make the Swift class available from Objective-C all that's needed is to put @objc in front of the class definition, and make the TimezoneMapper class derive from NSObject. I'm using it now in this way. Thanks!

**Comment by paucskmobon** [comment]
It is enough to make the TimezoneMapper class derive from NSObject.

**Comment by cheskapac** [comment]
It is enough to make the TimezoneMapper class derive from NSObject.

**Comment by lexar** [comment]
Please, could you show the code for 

- what I should change in TimezoneMapper.swift
- what (if any) to add in the bridging header file.
- how to import LatLongToTimezone into an Objective-C source file
- how to use LatLongToTimezone in that source file

for someone who is still a Swift newbie. It is very difficult to find clear information on this.

**Comment by akirmse** [comment]
NSObject was added awhile ago.

**Comment by alecvance** [comment]
Note that now in Xcode 10, when updating the project for Swift 4, it's necessary to include @objcMembers in the Swift file for this to be able to be imported into an Objective-C project. Otherwise you will get a method not found error when compiling. 

This article shows the use of the @objcMembers prefix: https://medium.com/swift2go/swift-4-and-objc-warnings-b520083f411f

**Comment by akirmse** [comment]
I don't use Objective-C but feel free to send a PR.
