### ISSUE TITLE
Compile warnings for Xcode 10/Swift 4.2

### ISSUE THREAD

**Issue by SjaakSchilperoort** [drtimcooper/LatLongToTimezone#21]
After updating to the latest version of Xcode, I get two compile warnings in the swift source file TimezoneMapper.swift. "open static" should now be "public static". I've created a fix, but encountered an unexpected project setup. The podspec on cocaopods is apparently based on an unmerged commit which is tagged "1.1.2". Shouldn't this have been merged to master? I wanted to create a pull request, but with master being out-of-date I'm not sure how to proceed. Could you please look into this? Thanks!

**Comment by akirmse** [comment]
I'm working on a new version (the code for which is actually already checked in), but unfortunately I'm running into this Cocoapods bug when trying to update the podspec: https://github.com/CocoaPods/CocoaPods/issues/7708

**Comment by Ariandr** [comment]
Hello @akirmse 
It seems they fixed the bug. So, could you please try to update the pod again?

**Comment by akirmse** [comment]
I was able to update using the beta version of cocoapods.  

The new version of this pod is 1.1.5.

**Comment by Ariandr** [comment]
Great, thank you!
