### ISSUE TITLE
Change SWIFT_VERSION

### ISSUE THREAD

**Issue by Tapestes** [drtimcooper/LatLongToTimezone#25]
Looks like as of xcode 10.2, we can no longer compile Swift 3.0 if we have an app targeting 4.0 or later.  Could you change the target to 4.0 or 4.2?

**Comment by akirmse** [comment]
I'm using this with a Swift 5 project successfully, and in the podspec I
see that it declares swift_version of 4.2.  Can you tell me where the
target needs to be changed?

**Comment by Tapestes** [comment]
Sure.  Open up the xcode project in the carthage folder, select the target
in xcode in the left side navigation panel, and  select the build settings
tab.  Then look through the build settings for Swift Compiler Language.
You should see it’s set to Swift 3.0.  If you change it to 4.2, that should
allow carthage to compile  with the latest xcode command line tools.  I did
this on a fork I created yesterday and verified it fixes the carthage
issue.  If you’d prefer, I can create a pull request.

Gracias

**Comment by akirmse** [comment]
A PR would be great---I don't use Carthage.  And if you can move it up to
Swift 5.0, which just came out this week, even better.

**Comment by Tapestes** [comment]
PR is in.

**Comment by akirmse** [comment]
Merged, and released new Cocoapod 1.1.6.  Thanks!
