### ISSUE TITLE
Is that ok to modify this library to meet project need?

### ISSUE THREAD

**Issue by nj005py** [drtimcooper/LatLongToTimezone#36]
TimezoneMapper.java is very useful,but it is still too big(1.64MB) for an app,therefore we want to change the way we use it.
Our plan is that separate the java file into java part and xml part,so we can customize the accuracy and get appropriate size data from the server.
Would you guys mind that if we do such modification?

**Comment by sorvant** [comment]
Hello dear fellow programmer, I think it is OK to modify the library to meet your project needs, but you also need to make sure that everyone is benefiting from that modification. Therefore, you need to analyze how others are using this library and if you make a breaking change then it will break many automated deployment systems and thus you will make many deployment managers mad - you probably don't want to invest your time to do that.

As far as I know these files are generated from a DB or something similar: maybe you just want to improve that data and leave the generated files to be handled automatically. You may also want to explore the idea to host the service on an API server and query it from your mobile app.

On  another note: this library is one of the most useful one, it measures up to Google's (lat, lng) -> tz function which comes for $$$. Congrats to the masters.

Best!

**Comment by dasbiswajit** [comment]
@drtimcooper @tom-b-wright I would like to contribute back. Can you help me how to update the java file for any time region change globally. I have raised a request https://github.com/drtimcooper/LatLongToTimezone/issues/35 which is unattended. If someone gave me a logic i can send the pull request to merge.

**Comment by drtimcooper** [comment]
@dasbiswajit Are you simultaneously saying that the file is too big and you need to reduce the resolution, AND it has too many errors e.g. Istanbul, Brasilia...?  Reducing the resolution will only make the error rate worse.  Can you elaborate on what you propose?  You want to do some filtering to reduce the number of edges in the polygons while minimising the area of the change?  And how will you improve accuracy while reducing resolution?

**Comment by dasbiswajit** [comment]
@drtimcooper only two zone errors which I have updated https://github.com/drtimcooper/LatLongToTimezone/issues/35
Happy to contribute bak if any help required.
Thanks
Biswajit

**Comment by dasbiswajit** [comment]
@drtimcooper #35 is now closed.
