### ISSUE TITLE
The swift version could do with updating to Swift 2.2 and subsequent

### ISSUE THREAD

**Issue by JetPCUK** [drtimcooper/LatLongToTimezone#7]
According to Swift 2.2 they are going to deprecate the i++ type interation syntax starting from 3.0.  Also the classic c-style for loop will be deprecated for the new swift  'for i in 0...10' style loops.  It would be nice if you could update the swift file syntax accordingly at some stage.

Both of these issues are present in the 'contains' function

**Comment by akirmse** [comment]
Done in version 1.0.3.  Thanks for the suggestion.
